<aside class="sidebar-drawer">
	<div class="sidebar-container">
		<div class="sidebar-sticky">
			<a class="sidebar-brand muted-link" href="/">
			<div class="sidebar-logo-container">
				<img src="/rebol-icon.svg" width="30" height="30" class="bi pe-none me-2" alt="">
				<span class="fs-5 fw-bold ">Oldes' Rebol3</span>
			</div>
			</a>
			<!--<form class="sidebar-search-container" method="get" action="search.html" role="search">
				<input class="sidebar-search" placeholder="Search" name="q" aria-label="Search">
				<input type="hidden" name="check_keywords" value="yes">
				<input type="hidden" name="area" value="default">
			</form>
			<div id="searchbox"></div>-->
			<div class="sidebar-scroll">
				<div class="sidebar-tree">
					<p class="caption" role="heading"><span class="caption-text">Documentation</span></p>
					<ul>
						<li class="toctree-l1"><a class="reference internal" href="functions.html">Functions</a></li>
						<!--<li class="toctree-l1"><a class="reference internal" href="get_started.html">Getting Started</a></li>-->
					</ul>
					<p class="caption" role="heading"><span class="caption-text">Development</span></p>
					<ul>
						<li class="toctree-l1"><a class="reference internal" href="https://github.com/Oldes/Rebol3/releases/">Releases</a></li>
						<li class="toctree-l1"><a class="reference internal" href="https://github.com/Oldes/Rebol3">Source code</a></li>
						<li class="toctree-l1"><a class="reference internal" href="https://github.com/Oldes/Rebol3/blob/master/CHANGES.md">Change Log</a></li>
					</ul>
				</div>
				<div id="furo-sidebar-ad-placement" class="flat" data-ea-publisher="readthedocs" data-ea-type="readthedocs-sidebar" data-ea-manual="true" data-ea-keywords="only words|readthedocs-project-662380|readthedocs-project-sphinx-design" data-ea-campaign-types="community|house|paid"></div>
			</div>
		</div>
	</div>
</aside>